# Generated by Django 4.0.3 on 2022-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210528_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(max_length=100),
        ),
    ]
